# Generated by Django 4.2.9 on 2024-01-11 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_blogcategory_tag_postpagetag_postpage_tags_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="postpage",
            name="description",
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
