# Generated by Django 4.2.9 on 2024-01-15 16:44

from django.db import migrations
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_postpage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    ("header1", wagtail.blocks.CharBlock()),
                    ("paragraph", wagtail.blocks.RichTextBlock()),
                    (
                        "image_carousel",
                        wagtail.blocks.ListBlock(
                            wagtail.images.blocks.ImageChooserBlock()
                        ),
                    ),
                    (
                        "bullet_list",
                        wagtail.blocks.ListBlock(wagtail.blocks.CharBlock()),
                    ),
                    (
                        "image_text",
                        wagtail.blocks.StructBlock(
                            [
                                ("image1", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption1", wagtail.blocks.CharBlock()),
                                ("image2", wagtail.images.blocks.ImageChooserBlock()),
                                ("caption2", wagtail.blocks.CharBlock()),
                            ]
                        ),
                    ),
                    (
                        "quote",
                        wagtail.blocks.StructBlock(
                            [
                                ("quote_by", wagtail.blocks.CharBlock()),
                                ("quotes", wagtail.blocks.RichTextBlock()),
                            ]
                        ),
                    ),
                ],
                blank=True,
                use_json_field=True,
            ),
        ),
    ]
