# Generated by Django 4.2.9 on 2024-01-16 20:05

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0007_formpage_fieldform"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fieldform",
            name="page",
            field=modelcluster.fields.ParentalKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_fields",
                to="blog.formpage",
            ),
        ),
    ]
